---
- name: Apply package configuration
  ansible.builtin.import_tasks: packages.yml

- name: Apply system configuration
  ansible.builtin.import_tasks: system.yml

- name: Apply user configuration
  ansible.builtin.import_tasks: users.yml

- name: Apply system updates
  ansible.builtin.import_tasks: updates.yml
