---
- name: Ensure baseline packages are installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ baseline_packages }}"

- name: Ensure vim-enhanced is installed on RedHat family
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ baseline_packages_redhat }}"
  when: ansible_os_family == "RedHat"

- name: Ensure curl-minimal is installed on Amazon family
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ baseline_packages_al2023 }}"
  when: ansible_os_family == "Amazon"
