---
- name: Update apt cache on Debian family
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 0
  when: ansible_os_family == "Debian"

- name: Ensure baseline packages on Debian family
  ansible.builtin.apt:
    name: "{{ baseline_packages + ['curl'] }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure baseline packages on RedHat family
  ansible.builtin.dnf:
    name: "{{ baseline_packages + ['curl', 'vim-enhanced'] }}"
    state: present
  when: ansible_os_family == "RedHat" and ansible_distribution != "Amazon"

- name: Ensure baseline packages on AL2023
  ansible.builtin.dnf:
    name: "{{ baseline_packages + ['curl-minimal', 'vim-enhanced'] }}"
    state: present
  when: ansible_distribution == "Amazon"

- name: Ensure baseline packages on SUSE family
  community.general.zypper:
    name: "{{ baseline_packages + ['curl'] }}"
    state: present
  when: ansible_os_family == "Suse"
