---
- name: Set system timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Deploy vimrc
  ansible.builtin.copy:
    src: .vimrc
    dest: "/home/{{ ansible_user }}/.vimrc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Deploy MOTD template
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'
