[al2023]
node-al2023 ansible_host=${al2023_id} ansible_user=ec2-user

[debian]
node-debian ansible_host=${debian_id} ansible_user=admin

[ubuntu]
node-ubuntu ansible_host=${ubuntu_id} ansible_user=ubuntu

[arch]
node-arch ansible_host=${arch_id} ansible_user=arch

[linux:children]
al2023
debian
ubuntu
arch

[linux:vars]
ansible_connection=aws_ssm
ansible_aws_ssm_region=us-east-1
ansible_aws_ssm_bucket_name=${s3_bucket_name}
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
ansible_remote_tmp=/tmp/.ansible/tmp
ansible_shell_type=sh
ansible_ssm_python_cmd="python3"

