---

baseline_packages:
   - vim
   - git
   - curl
   - wget

baseline_packages_redhat:
  - vim-enhanced

baseline_packages_al2023:
  - curl-minimal

timezone: "America/New_York"

baseline_users:
  - name: harrycallahan
    uid: 1051
    groups: wheel
    shell: /bin/bash
    state: present
