[al2023]
node-al2023 ansible_host=${al2023_ip} ansible_user=ec2-user

[debian]
node-debian ansible_host=${debian_ip} ansible_user=admin

[ubuntu]
node-ubuntu ansible_host=${ubuntu_ip} ansible_user=ubuntu

[arch]
node-arch ansible_host=${arch_ip} ansible_user=arch

[linux:children]
al2023
debian
ubuntu
arch

[linux:vars]
ansible_ssh_private_key_file=./ansible-lab-key.pem
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
